### ISSUE TITLE
ModuleNotFoundError: No module named 'pointops_cuda'

### ISSUE THREAD

**Issue by yuchenlichuck** [POSTECH-CVLab/point-transformer#40]
I come across the problem: Traceback (most recent call last):
  File "exp/s3dis/pointtransformer_repro/train.py", line 371, in <module>
    main()
  File "exp/s3dis/pointtransformer_repro/train.py", line 88, in main
    mp.spawn(main_worker, nprocs=args.ngpus_per_node, args=(args.ngpus_per_node, args))
  File "/home/liy0r/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/liy0r/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/home/liy0r/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/ibex/scratch/liy0r/cvpr/point-transformer/exp/s3dis/pointtransformer_repro/train.py", line 104, in main_worker
    from model.pointtransformer.pointtransformer_seg import pointtransformer_seg_repro as Model
  File "/ibex/scratch/liy0r/cvpr/point-transformer/model/pointtransformer/pointtransformer_seg.py", line 4, in <module>
    from lib.pointops.functions import pointops
  File "/ibex/scratch/liy0r/cvpr/point-transformer/lib/pointops/functions/pointops.py", line 7, in <module>
    import pointops_cuda
ModuleNotFoundError: No module named 'pointops_cuda'

**Comment by QuanticDisaster** [comment]
I encountered the same problem and corrected it the following way : https://github.com/POSTECH-CVLab/point-transformer/issues/27

As for reproducibility you can find a log and pretrained models by a user in the closed issue **_mIoU for s3dis dataset using Area 5 as test set_**

**Comment by ramdrop** [comment]
It is because the package has not been built. Executing the following commands will resolve it:
```shell
cd src/cuda_ops_knn/pointops
pip3 install .
```
